### ISSUE TITLE
How could I help with Razer support

### ISSUE THREAD

**Issue by mastercoms** [jonathanpotts/Spectral#1]
Hi, I noticed that Razer support was removed in this commit https://github.com/jonathanpotts/Spectral/commit/17899937d11161da4bd9195e5154bbdfd03f22ba.

What were your considerations for a reimplementation and how may I help with getting support back in?

**Comment by jonathanpotts** [comment]
There are two main issues as of right now:

1. I don't own any Razer devices to test with.
2. I skipped over the SpectralSetColor implementation for Razer devices.


If you want to help, if you could download a copy of the repo at commit b2196e7463b3b56b1ed0f8603e2fc70e4179301b and test against that and let me know if the functionality other than the SpectralSetColor method works. If that works, I'll write an implementation for that method. Also, if you could test to see if you can perform multiple SpectralSetColorForLed for different keys and let me know if the previous set colors remain set, or if they get reset.

**Comment by mastercoms** [comment]
Hm, I don't have any Razer devices to test with either. I'm just a game dev who wanted that sort of support for my audience. I'm still looking to see if we have any testers available for this, but none so far.
