### ISSUE TITLE
Initialization fails - Corsair K70 RGB Rapidfire - Unreal Engine

### ISSUE THREAD

**Issue by drewc5131** [jonathanpotts/Spectral#2]
When I initialize, the result bool outputs as FALSE. Trying to set rgb colors, nothing happens.

**Comment by jonathanpotts** [comment]
Hi, do you have CUE installed and running? Also, can you provide the code block you are using? Thanks.

**Comment by drewc5131** [comment]
Sorry for forgetting to specify. Im using Unreal Engine and used Blueprint.

**Comment by drewc5131** [comment]
And yes I do have CUE Installed and running. Version 1.16.42. Enable SDK is on

**Comment by jonathanpotts** [comment]
Can you try updating CUE to the latest version? Link provided here: http://downloads.corsair.com/download?item=Files/CUE/CorsairUtilityEngineSetup_2.24.50_release.msi

Also, can you screenshot your blueprint or send me an example project so that I can test on my end. Thanks.

**Comment by drewc5131** [comment]
I see. If only the installers would work. I tried the one you sent and the latest on on their site. 
![image](https://user-images.githubusercontent.com/31282527/44418722-295caa80-a547-11e8-80e4-0c0a313ca92d.png)
I'm trying to fix this then i will test the plugin to see if it works andget back to you.

**Comment by drewc5131** [comment]
Oh my goodness it worked.
