### ISSUE TITLE
Initialization Fails on C# with exception: BadImageFormatException

### ISSUE THREAD

**Issue by burdoto** [jonathanpotts/Spectral#3]
Whenever I try to Initialize with the following, simple code, the init just throws a BadImageFormatException.
Using .NET Framework 4.6.1, Console Application

```csharp
using System;
using Spectral;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Led.Initialize();
            if (Led.LogitechIsEnabled())
            {
                Led.SetColorForLed(LedName.B, 20, 20, 100);
            }
            Console.ReadKey(true);
        }
    }
}
```

**Comment by jonathanpotts** [comment]
This error means that it's using the wrong DLL (either 32-bit DLL with a 64-bit executable or 64-bit DLL with a 32-bit executable). Are you using the NuGet package or the source from GitHub? If you are using the source from GitHub, do you have the correct DLL in your binary folder?

**Comment by burdoto** [comment]
I have used the NuGet package, using a x64 CPU slot.
UPDATE: Changing the CPU Slot to x86 has fixed the issue.
Sorry, im kinda new to this whole C# thing, how do I get the x64 package?

**Comment by jonathanpotts** [comment]
Try running using Any CPU as the build option and let me know what happens.

**Comment by burdoto** [comment]
UPDATE: Changing the CPU Slot to x86 has fixed the issue.

**Comment by jonathanpotts** [comment]
I just tried testing on my system by creating a new .NET Framework 4.6.1 Console Application and loading in the NuGet package and used your code and it is working for me. What version of Visual Studio are you using?

**Comment by burdoto** [comment]
15.7.6

**Comment by burdoto** [comment]
15.7.6

I might have it not set up to look for x64 packages, if thats a possibility?

**Comment by jonathanpotts** [comment]
It does seem like a configuration issue with your NuGet package manager. Can you send me a list or screenshot of the contents of your output folder?

**Comment by burdoto** [comment]
![grafik](https://user-images.githubusercontent.com/42473485/45113673-47332d80-b14b-11e8-95ca-bf5461002137.png)

This List only goes on with System DLLs.
This is after a successful x86 run.

**Comment by jonathanpotts** [comment]
Was there an x64 output folder for when you were trying to compile with x64? It looks like to me only the 32-bit DLLs were included in the build.

**Comment by burdoto** [comment]
No. There was only this bin/Debug folder.
Other directories are empty.

**Comment by jonathanpotts** [comment]
OK, well I cannot replicate the issue on my end, so I am assuming it's a configuration issue on your end.

Here is a screenshot of what I get when I compile for x64:
![image](https://user-images.githubusercontent.com/17758200/45113960-9bfd8680-b100-11e8-87fd-923bd0511906.png)

Notice there is a CUESDK.x64_2015.dll which shows that 64-bit DLLs are being included.

If you agree this is a configuration issue on your end, please close the issue. Thanks.
