### ISSUE TITLE
Support for Saitek (Logitech) Products?

### ISSUE THREAD

**Issue by spreedated** [jonathanpotts/Spectral#5]
Hi @ll,

just tested everything with my Logitech mouse & keyboard, works fine.
I was wondering if you could add support for the saitek products (brand of logitech) like the HOTAS series (x52 & x56), I provide you with the SDK files (C++) for controlling the LEDs.

Would be very nice to finally have a .NET wrapper for it.

[DirectOutput.zip](https://github.com/jonathanpotts/Spectral/files/2742267/DirectOutput.zip)

**Comment by jonathanpotts** [comment]
Since I don't own any Saitek devices I will need to defer this to someone that has them. Should be relatively easy for someone with some C++ and C# knowledge to implement it into the source code and put in a pull request. I've marked this as help wanted for now.

**Comment by spreedated** [comment]
Thanks - I own a Saitek/Logitech X56. I have some experience in C#/VB, but unfortunetly I don't know how to approach the C++ code. I'm willing to help.
