### ISSUE TITLE
Logitech - Ability to Save the color back to the device

### ISSUE THREAD

**Issue by BaconTentacles** [jonathanpotts/Spectral#6]
I am looking to write a Windows Service to periodically pull the Windows 10 title bar color from the registry, then send that color to any LED peripherals I have.  The idea is that as a random color is chosen when the background changes, that color gets reflected in the keyboard and/or mouse.  Because why not, right?

Spectral appears to set the color perfectly when I run it as a basic one-and-done script, but as soon as I call Led.Shutdown, it reverts to the previous color (In fact, it wasn't until I put a Thread.Sleep into my code, that I realized it was doing anything at all).  

I suppose I could just have Spectral running as a part of the service, but I would love to have the ability to call LogiLedSaveCurrentLighting from within Spectral to make the color permanent, so to speak (especially since once you click into the G Pro gaming software and pick the mouse menu, it reverts the color anyway).   

I guess I could wrap the SDK directly, but your library is so...convenient.  :-D

**Comment by jonathanpotts** [comment]
The reason I did not implement that functionality is because it is not common between device manufacturers. If you are just using Logitech devices, the Logitech SDK already has a C# wrapper. https://www.logitechg.com/sdk/LED_SDK_9.00.zip

**Comment by BaconTentacles** [comment]
Aha.  I thought it might be something like that.  I do have a copy of the SDK and will pursue that next, but...hey, NuGet!  

Thanks for the quick response.  Rock on.  :-)
