### ISSUE TITLE
[Feature] Get Color by key

### ISSUE THREAD

**Issue by KleinDevDE** [jonathanpotts/Spectral#7]
Hello,

Devices: 
- Logitech G910 (Keyboard)
- Logitech G502 Hero (mouse)
- Logitech G633 (headset)

I'm currently working on a small software which will make a certain key on my keyboard blink when I receive a notification.

But now it would be great if I can get the currently displayed color with Spectral to use it when flashing.

Example:
I have the color blue on the ESC key
An important message comes in
My software starts flashing my ESC
Red -> White -> Red -> White -> Red -> White etc.

But it would be nicer if I could save the previous color (blue in this case), then it would look like this:
Red -> Blue -> Red -> Blue -> Red -> Blue

Besides: Only when the software is finished, I will give you previous color.

It would be really great if there was any possibility :)

**Comment by jonathanpotts** [comment]
There isn't an official way to get what color a key currently is. However, you can use the Logitech SDK to play effects on keys which might accomplish something similar to what you want: https://www.logitechg.com/sdk/LED_SDK_9.00.zip
